feature/cap09
candy184/curso-html5 pull request #10
Opened 2024-11-25 21:26 UTC by candy184

Subiendo el resumen del capitulo 9 del curso html5

2024-11-25 22:45 UTC, candy184 commented
@semanticmx

2024-11-25 23:55 UTC, semanticmx requested changes

2024-11-25 23:55 UTC, semanticmx commented on cap-09/src/index.html
> +    <img src="1.jpg" alt="Logo">
muy bien, pero igual que los otros PR, falta el formato del código de acuerdo con la guía de estilo

2025-01-21 16:10 UTC, candy184 reviewed
Cambios realizados

2025-01-21 16:11 UTC, candy184 commented
@semanticmx  listo

2025-01-21 16:17 UTC, semanticmx approved these changes
gracias!

2025-02-04 17:45 UTC, merged