feature/cap10
candy184/curso-html5 pull request #11
Opened 2024-11-25 22:45 UTC by candy184

Subiendo el resumen del capitulo 10 de los cursos de html5

2024-11-25 22:45 UTC, candy184 commented
@semanticmx

2024-11-25 23:54 UTC, semanticmx requested changes
El PR me aparece como "Work in Progress" ese modo se utiliza para crear el PR pero indicar que todavía se esperan más cambios, si esa es la intención está muy bien.

2024-11-25 23:54 UTC, semanticmx commented on cap-10/src/index.html
> +    <input type="text" id="nombre" name="nombre" placeholder="Introduce tu nombre" required>
Está perfecto, solo hay que aplicar el formato de la guía de estilo por favor

https://github.com/inversify/InversifyJS?tab=readme-ov-file#step-1-declare-your-interfaces-and-types

2025-01-24 16:11 UTC, candy184 reviewed
@semanticmx ya quedo

2025-01-24 16:11 UTC, candy184 commented on cap-10/src/index.html
> +    <input type="text" id="nombre" name="nombre" placeholder="Introduce tu nombre" required>
@semanticmx  listo

2025-02-04 17:45 UTC, merged