Feature/cap11
candy184/curso-html5 pull request #12
Opened 2024-11-25 23:35 UTC by candy184

Subí el capitulo 11 de los cursos de html5

2024-11-25 23:35 UTC, candy184 commented
@candy184

2024-11-25 23:35 UTC, candy184 commented
@semanticmx

2024-11-25 23:57 UTC, semanticmx requested changes

2024-11-25 23:57 UTC, semanticmx commented on cap-11/src/index.html
> +            <time itemprop="startDate" datetime="2024-12-15T10:00">15 de diciembre de 2024, 10:00 AM</time>
formato por favor.

2025-01-21 16:46 UTC, candy184 reviewed
corregido

2025-01-21 16:46 UTC, candy184 commented
@semanticmx listo

2025-01-21 16:58 UTC, semanticmx commented
Está en Draft

2025-01-24 16:04 UTC, candy184 commented
@semanticmx ya

2025-01-24 18:24 UTC, semanticmx requested changes

2025-01-24 18:24 UTC, semanticmx commented on cap-11/src/index.html
> +            <time itemprop="startDate" datetime="2024-12-15T10:00">15 de diciembre de 2024, 10:00 AM</time>
hay que aplicar el format de HTML por favor

2025-02-04 17:46 UTC, merged