Feature/cap12
candy184/curso-html5 pull request #13
Opened 2024-11-26 00:12 UTC by candy184

Resumen del ultimo capitulo del curso de html5

2024-11-26 00:12 UTC, candy184 commented
@semanticmx

2024-11-26 16:43 UTC, semanticmx requested changes
muy bien, ya solo formatea el código

2024-11-26 16:43 UTC, semanticmx commented on cap-12/README.md
> +    <a id="photonext" href="next.html">Next ></a>
:(

2025-01-21 16:31 UTC, candy184 reviewed
Corregido

2025-01-21 16:31 UTC, candy184 commented
@semanticmx  listo

2025-02-04 17:46 UTC, merged