Features/cap02
candy184/curso-html5 pull request #2
Opened 2024-10-08 03:56 UTC by candy184

Resumen y ejemplo del capitulo2 de html5

2024-10-08 13:46 UTC, semanticmx requested changes
creo que está incompleto el capítulo. recuerda que debes hacer muchos add/status/commit y una vez que esté terminado hacer un push+pull request

2024-10-08 13:46 UTC, semanticmx commented on cap-02/README.md
> +<article>:para
creo que aquí te faltó completar el texto

2024-10-08 13:46 UTC, semanticmx commented on cap-02/README.md
> +3. Lienzo
Algunos componentes de programación preferimos no traducirlos, especialmente si van a ser muy conocidos o utilizados, como el caso de `canva`, entonces en lugar de "Lienzo" podemos escribir "Canvas"

2024-10-08 13:46 UTC, semanticmx commented on cap-02/README.md
> +Los trabajadores de la webPermitir ejecutar scripts
Hay que corregir el texto, falta un punto de separación y despegar web de Permitir

2024-10-08 13:46 UTC, semanticmx commented on cap-02/README.md
> +Los WebSockets permiten
El texto está incompleto

2024-10-08 13:46 UTC, semanticmx commented on cap-02/src/index.html
> +<!DOCTYPE HTML>
Falta la identación, como tip este proceso lo puedes hacer con un click desde visual code:

https://code.visualstudio.com/docs/editor/codebasics#_formatting

2024-10-08 23:15 UTC, semanticmx requested changes
faltó las minúsculas

2024-10-08 23:15 UTC, semanticmx commented on cap-02/src/index.html
> +<HTML>
las etiquetas van en minúsculas

2024-10-08 23:15 UTC, semanticmx commented on cap-02/src/index.html
> +    <STYLE TYPE="TEXT/CSS">
también los atributos van en minúsculas

2024-10-15 16:56 UTC, candy184 commented
@semanticmx  realización de correcciones

2024-10-15 17:44 UTC, semanticmx approved these changes
gracias!

2024-10-15 18:10 UTC, merged