Features/cap03
candy184/curso-html5 pull request #3
Opened 2024-10-08 17:46 UTC by candy184

Resumen y ejemplo del cap3

2024-10-08 23:20 UTC, semanticmx requested changes
muy bien, solo unos ajustes por favor

2024-10-08 23:20 UTC, semanticmx commented on cap-02/README.md
> +# Capítulo 2: ¿Como llegamos hasta aqui?
Cómo es con acento

2024-10-08 23:20 UTC, semanticmx commented on cap-02/src/index.html
> +<HTML>
lo mismo, las etiquetas en minúscula

2024-10-08 23:20 UTC, semanticmx commented on cap-03/src/index.html
> +<!DOCTYPE html>
este código quedó muy bien

2024-10-15 16:43 UTC, candy184 commented
@semanticmx correcciones listas

2024-10-15 17:43 UTC, semanticmx requested changes
hay que eliminar los archivos del cap 02 por favor

2024-10-15 17:43 UTC, semanticmx commented on cap-02/README.md
> +# Capítulo 2: ¿Cómo llegamos hasta aqui?
@candy184 hay que eliminar los archivos del capítulo 2 de este PR, ya que tenemos otro PR solo para el capítulo 2.

2024-10-15 17:43 UTC, semanticmx commented on cap-03/README.md
> +# Detección de Características HTML5
muy bien!

2024-10-22 16:29 UTC, closed without merging