capitulo 4
candy184/curso-html5 pull request #4
Opened 2024-10-17 20:39 UTC by candy184

añadí el resumen 4 junto con su index.html

2024-10-21 20:43 UTC, semanticmx requested changes

2024-10-21 20:43 UTC, semanticmx commented on cap-03/README.md
> +# Detección de Características HTML5
Cuando trabajas con muchos branches sucede lo siguiente:

1. Supongamos que inicias con un archivo README.md en el branch main
2. Cuando creas un branch por ejemplo features/cap-01, el archivo README.md se pasa en automático al nuevo branch junto con cualquier otro archivo que no haya sido comiteado a otro branch

Lo que debe suceder es que todos los archivos pertenecientes a features/cap-01 se agreguen y comiteen en ese feature branch y cuando te regreses a main verifiques que los archivos desaparecieron, ya que se registraron en el branch features/cap-01

De esta forma, con un `main` vacío, tu puedes crear un nuevo branch para el features/cap-02, crear archivo del capítulo 2 y agregar y comitear al branch features/cap-02. Cuando te regreses al branch `main` de nuevo te tienes que quedar sin archivos.

Porque lo que hiciste en Cap 01 debe estar en features/cap-01 y lo que hiciste en Cap 02 debe quedar en features/cap-02.

Si se mezcla primero features/cap-02 entonces en tu `main` solo se verán los archivos del Cap 02

En el caso de este PR veo que hay archivos del cap 03 y el cap 04, y los del cap 03 están repetidos de otro PR.

Entonces hay que eliminarlos de este PR por favor y revisa el proceso que sigues para crear PR porque no debe de agregarte archivos que no van, ya que eso significa que no se agregaron correctamente al feature branch que le tocaba.

2024-10-21 20:43 UTC, semanticmx commented on cap-04/README.md
> +El capitulo aborda la evolución y mejora de la semántica en HTML5, explicando cómo las nuevas etiquetas y prácticas ayudan a hacer el código HTML más claro y significativo, tanto para los navegadores
muy bien, agregar un resumen

2024-10-21 20:43 UTC, semanticmx commented on cap-04/src/index.html
> +Ejemplo de cómo el "modo peculiar" mantiene comportamientos antiguos:
si agregas 3 ejemplos deben estar en 3 archivos diferentes, porque esto ya es código y textos fuera de etiquetas o muchos `<!DOCTYPE ...` en el mismo archivo no va a validar.

Puedes crear archivos quirks.html, html5.html y semi.html

2024-10-24 02:15 UTC, candy184 commented on cap-03/README.md
> +# Detección de Características HTML5
listo

2024-10-24 02:35 UTC, candy184 commented
@semanticmx cambios realizados

2024-10-24 02:37 UTC, candy184 reviewed
@semanticmx  cambios realizados

2024-10-24 13:46 UTC, semanticmx approved these changes
gracias

2024-10-25 01:23 UTC, merged