Features/cap05
candy184/curso-html5 pull request #6
Opened 2024-10-24 02:04 UTC by candy184

2024-10-24 13:45 UTC, semanticmx requested changes

2024-10-24 13:45 UTC, semanticmx commented on cap-05/README.md
> +Introducción al <canvas>
Dale un poco de formato, estos pueden ser títulos

https://www.markdownguide.org/cheat-sheet/

2024-10-24 13:45 UTC, semanticmx commented on cap-05/README.md
> +javascript
El código ponlo con formato también

2024-10-24 13:45 UTC, semanticmx commented on cap-05/README.md
> +Ejemplo de gradiente lineal:
Igual para títulos y subtítulos

2024-10-24 13:45 UTC, semanticmx commented on cap-05/src/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
Cuando tengas más de un atributo agregalos uno por línea.

así:

```html
<meta 
  name="viewport" 
  content="width=device-width, initial-scale=1.0"
>
```

2024-10-24 13:45 UTC, semanticmx commented on cap-05/src/index.html
> +<h1>Canvas: Dibujar Formas Simples</h1>
los elementos dentro del `body` deben de ir identados

2024-10-25 02:11 UTC, candy184 reviewed
@semanticmx  cambios listos

2024-10-25 02:11 UTC, candy184 commented on cap-05/README.md
> +javascript
listo

2024-10-25 02:11 UTC, candy184 commented on cap-05/src/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
listo

2024-10-25 02:12 UTC, candy184 commented
@semanticmx  cambios realizados

2024-10-25 16:44 UTC, semanticmx requested changes

2024-10-25 16:44 UTC, semanticmx commented on cap-05/README.md
> +`for (var x = 0.5; x < 500; x += 10) {`
un ajuste más por favor.

lo que estás haciendo es esto:

```

javascript

`for (var x = 0.5; x < 500; x += 10) {`

`context.moveTo(x, 0);`
```

pero el texto `javascript` así suelto no hace nada

y cuando tengas bloques de código, es decir, más de una línea tienes que usar los tres acentos invertidos, es decir te tiene que quedar así:

 
```
```javascript
for (var x = 0.5; x < 500; x += 10) {
     context.moveTo(x, 0);
```
```

2024-10-25 16:44 UTC, semanticmx commented on cap-05/src/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
creo que este cambio no se guardó, sigo viendo una sola línea `<meta name="viewport" content="width=device-width, initial-scale=1.0">`

2024-10-25 16:44 UTC, semanticmx commented on cap-05/README.md
> +javascript
aplícale el ajuste de los tres acentos invertidos a todo el código.

2024-10-29 01:02 UTC, candy184 commented on cap-05/README.md
> +`for (var x = 0.5; x < 500; x += 10) {`
corregido

2024-10-29 01:04 UTC, candy184 commented on cap-05/src/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
corregido

2024-10-29 01:05 UTC, candy184 commented on cap-05/README.md
> +javascript
listo

2024-10-29 01:05 UTC, candy184 commented
@semanticmx  cambios listos

2024-10-29 14:45 UTC, semanticmx approved these changes
excelente!

2024-10-29 16:52 UTC, merged