Features/cap06
candy184/curso-html5 pull request #7
Opened 2024-10-29 01:27 UTC by candy184

Resumen y ejemplo del capitulo 6 del curso de HTML5

2024-10-29 01:27 UTC, candy184 commented
@semanticmx  subiendo el capitulo 6 del curso de html5

2024-10-29 14:47 UTC, semanticmx requested changes
muy bien

2024-10-29 14:47 UTC, semanticmx commented on cap-06/README.md
> +</video>
ah te faltó cerrar el código con otros tres acentos invertidos acá.

2024-10-29 14:47 UTC, semanticmx commented on cap-06/README.md
> +<video width="320" height="240" controls>
recuerda el formato que queremos para los atributos, ya se actualizó la guía de estilos para esto:

https://github.com/semanticmx/html5-coding-standards?tab=readme-ov-file#proper-use-of-standards-in-html5

2024-10-29 14:47 UTC, semanticmx commented on cap-06/src/index.htm
> +    <video width="640" height="360" controls>
Al código de ejemplo también hay que aplicarle la guía de estilos

https://github.com/semanticmx/html5-coding-standards?tab=readme-ov-file#proper-use-of-standards-in-html5

2024-11-05 16:04 UTC, candy184 commented on cap-06/README.md
> +</video>
listo

2024-11-05 16:04 UTC, candy184 commented on cap-06/README.md
> +<video width="320" height="240" controls>
listo

2024-11-05 16:05 UTC, candy184 commented on cap-06/src/index.htm
> +    <video width="640" height="360" controls>
listo

2024-11-05 16:05 UTC, candy184 commented
@semanticmx cambios listos

2024-11-05 16:06 UTC, candy184 commented
@semanticmx  cambios listos

2024-11-05 17:59 UTC, semanticmx requested changes

2024-11-05 17:59 UTC, semanticmx commented on cap-06/src/index.htm
> +    <video width="640" height="360" controls>
@candy184 arriba el tag de video lo tienes así:

```html
<video 
    width="320" 
    height="240" 
    controls
>
    <source 
        src="video.mp4" 
        type="video/mp4"
    >
    <source 
        src="video.webm" 
        type="video/webm"
    >
    <source 
        src="video.ogv" 
        type="video/ogg"
    >
</video>```

al código le tienes que aplicar el mismo formato

2024-11-12 15:25 UTC, candy184 commented
listo @semanticmx

2024-11-12 23:25 UTC, semanticmx approved these changes
gracias!

2024-11-14 19:49 UTC, merged